### ISSUE TITLE
Occasionally unable to autostart.

### ISSUE THREAD

**Issue by maxsky** [denji/homebrew-tengine#9]
I don't know why sometime when i boot system, but tengine not autostart.

I used `sudo brew services start tengine` set it. Because my system version is 10.13.6, it cannot support 80 port without root user.

This problem not in nginx.

**Comment by denji** [comment]
> However, Unix-like operating system by default do not allow programs that run non-root to listen on TCP/IP ports <1024.

```
$ sysctl net.inet.ip.portrange
```

Forward port 80 to 8080: http://apple.stackexchange.com/a/230331/52680
